### PR TITLE
handle undefined dimensions in extraction; fixes #139

### LINKED ISSUE #139: unexpected behavior when extracting from tensors with undefined shape
Suppose I have a placeholder like `x` define below and I want to extract the first column:

```
x <- tf$placeholder(tf$int16, shape = list(NULL, 1L))
x[,0L]
```
This returns the following error:

```
Error in pmin(end, x_size) : 
  (list) object cannot be coerced to type 'double'
```

The equivalent python code works fine:

```
x = tf.placeholder(tf.int16, [None, 1])
x[:,0]
<tf.Tensor 'strided_slice:0' shape=(?,) dtype=int16>
```
Also the following works as expected:

```
> x <- tf$placeholder(tf$int16, shape = list(1L, 1L))
> x[,0L]
Tensor("StridedSlice:0", shape=(1,), dtype=int16)
```

### PR DESCRIPTION
**Pull request by goldingn**
implements a bugfix and adds a test

### CODE REVIEW

File: R/generics.R [hunk 1]
```diff
@@ -76,6 +78,13 @@ print.tensorflow.python.ops.variables.Variable <- print.tensorflow.python.framew
 
   # tensor shape as a vector
   x_size <- x$get_shape()$as_list()
+
+  # if it has dimension(s) of undefined size, this will be a list with NULLs
+  if (is.list(x_size)) {
+    x_size <- lapply(x_size, function (x) ifelse(is.null(x), NA, x))
```
Comment (terrytangyuan) [inline R/generics.R]: Do you mean NULL or NA here?

**Comment by goldingn** [comment]
If `x` is a placeholder with known shape, `x$get_shape()$as_list()` returns an integer vector.

If `x` has one or more unknown dimensions `x$get_shape()$as_list()` returns a list with `NULL` for those dimensions of unknown size. The rest of the code is expecting a vector, so this line converts `NULL`s to `NA`s so that x_size can be converted into a vector.

**Comment by terrytangyuan** [comment]
I see now. Thanks for the clarification!
